version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/charmander-api-jar

permissions:
  - object: /
    owner: ec2-user
    group: ec2-user

hooks:
  ApplicationStart:
    - location: scripts/start-server.sh
      timeout: 60
      runas: ec2-user
