oauth:
  client:
    provider:
      google:
        authorization-uri: https://accounts.google.com/o/oauth2/auth
        token-uri: https://accounts.google.com/o/oauth2/token
        user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
      github:
        authorization-uri: https://github.com/login/oauth/authorize
        token-uri: https://github.com/login/oauth/access_token
        user-info-uri: https://api.github.com/user
      naver:
        authorization-uri: https://nid.naver.com/oauth2.0/authorize
        token-uri: https://nid.naver.com/oauth2.0/token
        user-info-uri: https://openapi.naver.com/v1/nid/me
      kakao:
        authorization-uri: https://kauth.kakao.com/oauth/authorize
        token-uri: https://kauth.kakao.com/oauth/token
        user-info-uri: https://kapi.kakao.com/v2/user/me
